version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore: "
